variables:
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: registry.gitlab.com/social-reach/social-reach-landing

stages:
  - build
  - deploy

docker-build-prd:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest .
    - docker tag $CONTAINER_IMAGE $CONTAINER_IMAGE:v${CI_PIPELINE_IID}
    - docker push $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:v${CI_PIPELINE_IID}
  only:
  - release

k8s-deploy-prd:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - echo "$KUBECONFIG_PROD" > kubeconfig-prod.yaml
    - export KUBECONFIG=$PWD/kubeconfig-prod.yaml
    - sed -i "s#$CONTAINER_IMAGE#$CONTAINER_IMAGE:v$CI_PIPELINE_IID#g" k8s/deployment.yaml
    - kubectl apply -f k8s/deployment.yaml -n $PROD_NAMESPACE
  environment:
    name: sr-prod
  only:
    - release
