apiVersion: v1
kind: Service
metadata:
  name: socialreach-landing
  labels:
    app: socialreach-landing
spec:
  selector:
    app: socialreach-landing
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialreach-landing
spec:
  selector:
    matchLabels:
      app: socialreach-landing
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      name: socialreach-landing
      labels:
        app: socialreach-landing
    spec:
      containers:
      - name: socialreach-landing
        image: registry.gitlab.com/social-reach/social-reach-landing
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 25m
